# Generated by Django 3.2.25 on 2025-04-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_purchaseorder_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
