# Generated by Django 3.2.25 on 2025-04-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_purchaseorder_last_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order_date',
        ),
    ]
