# Generated by Django 3.2.25 on 2025-05-08 06:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_remove_purchaseorder_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='inventory_updated',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceiptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_logs', to='warehouse.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received_this_time', models.PositiveIntegerField()),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_entries', to='warehouse.purchaseorderitem')),
                ('receipt_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_items', to='warehouse.purchaseorderreceiptlog')),
            ],
        ),
    ]
