# Generated by Django 3.2.25 on 2025-05-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20250512_1911'),
        ('warehouse', '0006_auto_20250508_1423'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouseproduct',
            unique_together={('warehouse', 'product')},
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='expiry_date',
        ),
    ]
