# Generated by Django 3.2.25 on 2025-05-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_warehouseproduct_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='expiry_date',
        ),
    ]
