# Generated by Django 3.2.25 on 2025-05-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_remove_warehouseproduct_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
