# Generated by Django 3.2.25 on 2025-07-04 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0018_packagingmaterial'),
        ('warehouse', '0011_auto_20250515_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING_INVOICE', 'Waiting Invoice'), ('PAYMENT_MADE', 'Payment Made'), ('PARTIALLY_DELIVERED', 'Partially Delivered'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='cancelled_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='delivered_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='draft_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='partially_delivered_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payment_made_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='waiting_invoice_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorderreceiptitem',
            name='receipt_log',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING_INVOICE', 'Waiting Invoice'), ('PAYMENT_MADE', 'Payment Made'), ('PARTIALLY_DELIVERED', 'Partially Delivered'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouseproduct'),
        ),
        migrations.AlterField(
            model_name='purchaseorderreceiptitem',
            name='po_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.purchaseorderitem'),
        ),
        migrations.DeleteModel(
            name='PurchaseOrderReceiptLog',
        ),
        migrations.AddField(
            model_name='purchaseorderstatuslog',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='warehouse.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderstatuslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderreceiptitem',
            name='status_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_items', to='warehouse.purchaseorderstatuslog'),
        ),
    ]
