# Generated by Django 3.2.25 on 2025-07-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_auto_20250707_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='max_ship_qty_a',
            field=models.PositiveIntegerField(blank=True, help_text='Max quantity to ship for condition A', null=True),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='max_ship_qty_b',
            field=models.PositiveIntegerField(blank=True, help_text='Max quantity to ship for condition B', null=True),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='photo',
            field=models.ImageField(blank=True, help_text='Warehouse-specific product image', null=True, upload_to='product_photos/warehouse/'),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=10, null=True),
        ),
    ]
