# Generated by Django 3.2.25 on 2025-07-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_auto_20250728_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Warehouse-specific selling price', max_digits=10, null=True),
        ),
    ]
