# Generated by Django 3.2.25 on 2025-05-12 11:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20250508_1423'),
        ('inventory', '0003_auto_20250424_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.CreateModel(
            name='InventoryBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch Number')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity in this Batch')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost Price (per unit)')),
                ('date_received', models.DateField(default=django.utils.timezone.now, verbose_name='Date Received')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='warehouse.warehouseproduct')),
            ],
            options={
                'verbose_name': 'Inventory Batch Item',
                'verbose_name_plural': 'Inventory Batch Items',
                'ordering': ['warehouse_product__product__name', 'warehouse_product__warehouse__name', 'expiry_date', 'batch_number'],
                'unique_together': {('warehouse_product', 'batch_number')},
            },
        ),
    ]
