# Generated by Django 3.2.25 on 2025-05-14 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_purchaseorder_created_at'),
        ('inventory', '0005_auto_20250513_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorybatchitem',
            options={'ordering': ['warehouse_product__product__name', 'warehouse_product__warehouse__name', 'batch_number', 'location_label', 'expiry_date'], 'verbose_name': 'Inventory Batch Item', 'verbose_name_plural': 'Inventory Batch Items'},
        ),
        migrations.AddField(
            model_name='inventorybatchitem',
            name='location_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location Label (e.g., Box/Shelf ID)'),
        ),
        migrations.AlterField(
            model_name='inventorybatchitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='inventorybatchitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity in this Batch/Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In (PO Received)'), ('OUT', 'Stock Out (Sales Order)'), ('RETURN', 'Return In'), ('CANCEL', 'Cancel / Restore'), ('ADJUST', 'Manual Adjustment'), ('PO_ITEM_DEL_ADJ', 'PO Item Deletion Adjustment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='inventorybatchitem',
            unique_together={('warehouse_product', 'batch_number', 'location_label')},
        ),
    ]
