# Generated by Django 3.2.25 on 2025-05-15 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_purchaseorder_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0008_stocktakeitem_stocktakesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_location_label', models.CharField(blank=True, max_length=50, null=True)),
                ('system_batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('system_expiry_date', models.DateField(blank=True, null=True)),
                ('system_quantity', models.IntegerField(blank=True, help_text='Quantity as per system records at time of evaluation.', null=True)),
                ('counted_location_label', models.CharField(blank=True, max_length=50, null=True)),
                ('counted_batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('counted_expiry_date', models.DateField(blank=True, null=True)),
                ('counted_quantity', models.IntegerField(blank=True, help_text='Quantity as per physical count.', null=True)),
                ('discrepancy_quantity', models.IntegerField(help_text='Difference: counted_quantity - system_quantity. Positive for over, negative for short.')),
                ('discrepancy_type', models.CharField(choices=[('MATCH', 'Match'), ('OVER', 'Over Count'), ('SHORT', 'Short Count'), ('NOT_IN_SYSTEM', 'Not in System'), ('NOT_COUNTED', 'Not Counted'), ('DETAIL_MISMATCH', 'Detail Mismatch')], help_text='Type of discrepancy found.', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes explaining the discrepancy or actions taken.')),
                ('is_resolved', models.BooleanField(default=False, help_text='Has this discrepancy been addressed/resolved?')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how the discrepancy was resolved.')),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancies_resolved', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='The stock take session this discrepancy belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='inventory.stocktakesession')),
                ('stock_take_item_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancies_identified', to='inventory.stocktakeitem')),
                ('system_inventory_batch_item', models.ForeignKey(blank=True, help_text='The specific system batch item this discrepancy refers to (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancies_found', to='inventory.inventorybatchitem')),
                ('warehouse_product', models.ForeignKey(help_text="The system's Warehouse Product record this discrepancy primarily relates to.", on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouseproduct')),
            ],
            options={
                'verbose_name': 'Stock Discrepancy',
                'verbose_name_plural': 'Stock Discrepancies',
                'ordering': ['session', 'discrepancy_type', 'warehouse_product__product__name'],
            },
        ),
    ]
