# Generated by Django 3.2.25 on 2025-05-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20250517_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpstockcheckitem',
            name='erp_product_name_raw',
            field=models.CharField(blank=True, help_text='Product Name as it appeared in the ERP file for reference.', max_length=255, null=True),
        ),
    ]
