# Generated by Django 3.2.25 on 2025-05-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_auto_20250515_1806'),
        ('inventory', '0011_erpstockcheckitem_erp_product_name_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproductdiscrepancy',
            name='erp_product_name_for_unmatched',
            field=models.CharField(blank=True, help_text='ERP Product Name (if item not matched to system WP)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warehouseproductdiscrepancy',
            name='erp_product_sku_for_unmatched',
            field=models.CharField(blank=True, help_text='ERP Product SKU (if item not matched to system WP)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehouseproductdiscrepancy',
            name='erp_warehouse_name_for_unmatched',
            field=models.CharField(blank=True, help_text='ERP Warehouse Name (if item not matched to system WP)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseproductdiscrepancy',
            name='erp_stock_check_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancy_record', to='inventory.erpstockcheckitem'),
        ),
        migrations.AlterField(
            model_name='warehouseproductdiscrepancy',
            name='warehouse_product',
            field=models.ForeignKey(blank=True, help_text='The Warehouse Product this discrepancy relates to.', null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouseproduct'),
        ),
    ]
