# Generated by Django 3.2.25 on 2025-05-19 10:27

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20250517_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorybatchitem',
            options={'ordering': ['warehouse_product__product__name', 'warehouse_product__warehouse__name', '-is_default_pick', django.db.models.expressions.OrderBy(django.db.models.expressions.F('expiry_date'), nulls_last=True), 'date_received', 'batch_number', 'location_label'], 'verbose_name': 'Inventory Batch Item', 'verbose_name_plural': 'Inventory Batch Items'},
        ),
        migrations.AddField(
            model_name='inventorybatchitem',
            name='is_default_pick',
            field=models.BooleanField(default=False, help_text='Is this the primary batch to pick from for this Warehouse Product?'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatchitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_pick', True)), fields=('warehouse_product',), name='unique_default_pick_per_warehouse_product'),
        ),
    ]
