# Generated by Django 3.2.25 on 2025-05-19 16:29

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20250519_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorybatchitem',
            options={'ordering': ['warehouse_product__product__name', 'warehouse_product__warehouse__name', django.db.models.expressions.OrderBy(django.db.models.expressions.F('pick_priority'), nulls_last=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('expiry_date'), nulls_last=True), 'date_received', 'batch_number', 'location_label'], 'verbose_name': 'Inventory Batch Item', 'verbose_name_plural': 'Inventory Batch Items'},
        ),
        migrations.RemoveConstraint(
            model_name='inventorybatchitem',
            name='unique_default_pick_per_warehouse_product',
        ),
        migrations.RemoveField(
            model_name='inventorybatchitem',
            name='is_default_pick',
        ),
        migrations.AddField(
            model_name='inventorybatchitem',
            name='pick_priority',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Default'), (1, 'Secondary')], help_text='Picking priority: 0 for Default, 1 for Secondary. Leave blank for normal FEFO.', null=True),
        ),
        migrations.AddConstraint(
            model_name='inventorybatchitem',
            constraint=models.UniqueConstraint(condition=models.Q(('pick_priority', 0)), fields=('warehouse_product',), name='unique_default_pick_priority_per_wp'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatchitem',
            constraint=models.UniqueConstraint(condition=models.Q(('pick_priority', 1)), fields=('warehouse_product',), name='unique_secondary_pick_priority_per_wp'),
        ),
    ]
