# Generated by Django 3.2.25 on 2025-05-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20250520_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybatchitem',
            name='location_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='inventorybatchitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Qty'),
        ),
    ]
