# Generated by Django 3.2.25 on 2025-06-02 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_auto_20250515_1806'),
        ('operation', '0013_parcel_packaging_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0015_auto_20250521_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-transaction_date'], 'verbose_name': 'Stock Transaction', 'verbose_name_plural': 'Stock Transactions'},
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='created_at',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='batch_item_involved',
            field=models.ForeignKey(blank=True, help_text='The specific batch item involved in this transaction, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='inventory.inventorybatchitem'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='product',
            field=models.ForeignKey(help_text='Direct link to the Product (denormalized for easier querying if needed).', on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions_direct', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.IntegerField(help_text='Change in quantity. Positive for stock in/positive adjustments, negative for stock out/negative adjustments.'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='reference_note',
            field=models.CharField(blank=True, help_text='E.g., PO number, Order ID, Adjustment reason, Stock Take Session ID.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='operation.order'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='related_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='warehouse.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJ_P', 'Positive Adjustment'), ('ADJ_N', 'Negative Adjustment'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('RETURN_IN', 'Return In'), ('ST_INITIAL', 'Stock Take Initial'), ('ST_UPDATE', 'Stock Take Update')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='warehouse.warehouse'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='warehouse_product',
            field=models.ForeignKey(help_text='The specific warehouse product this transaction affects.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='warehouse.warehouseproduct'),
        ),
    ]
