# Generated by Django 3.2.25 on 2025-06-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20250602_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJ_P', 'Positive Adjustment'), ('ADJ_N', 'Negative Adjustment'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('RETURN_IN', 'Return In'), ('ST_INITIAL', 'Stock Take Initial'), ('ST_UPDATE', 'Stock Take Update'), ('SALE_PACKED_OUT', 'Sale - Packed Out')], max_length=20),
        ),
    ]
