# Generated by Django 3.2.25 on 2025-06-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_stocktransaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the packaging material (e.g., Foam Box A1, Gel Pack 500g).', max_length=150, unique=True)),
                ('material_code', models.CharField(blank=True, help_text='Internal SKU or code for the material.', max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_stock', models.PositiveIntegerField(default=0, help_text='Current available stock quantity.')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Stock level at which to reorder.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Packaging Material',
                'verbose_name_plural': 'Packaging Materials',
                'ordering': ['name'],
            },
        ),
    ]
