# Generated by Django 3.2.25 on 2025-07-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_packagingmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Stock Out'), ('ADJ_P', 'Positive Adjustment'), ('ADJ_N', 'Negative Adjustment'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('RETURN_IN', 'Return In'), ('ST_INITIAL', 'Stock Take Initial'), ('ST_UPDATE', 'Stock Take Update'), ('SALE_PACKED_OUT', 'Out')], max_length=20),
        ),
    ]
