# Generated by Django 4.2.23 on 2025-08-05 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_warehouseproduct_selling_price'),
        ('inventory', '0019_alter_stocktransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagingmaterial',
            options={'ordering': ['warehouse__name', 'name'], 'verbose_name': 'Packaging Material', 'verbose_name_plural': 'Packaging Materials'},
        ),
        migrations.AddField(
            model_name='packagingmaterial',
            name='warehouse',
            field=models.ForeignKey(default=1, help_text='The warehouse this packaging material belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='packaging_materials', to='warehouse.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='packagingmaterial',
            unique_together={('name', 'warehouse')},
        ),
    ]
