# Generated by Django 4.2.23 on 2025-08-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_packagingmaterial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingmaterial',
            name='name',
            field=models.CharField(help_text='Name of the packaging material (e.g., Foam Box A1, Gel Pack 500g).', max_length=150),
        ),
    ]
