# Generated by Django 4.2.23 on 2025-08-06 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_warehouseproduct_selling_price'),
        ('inventory', '0021_alter_packagingmaterial_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagingmaterial',
            options={'ordering': ['name'], 'verbose_name': 'Packaging Material (Global)', 'verbose_name_plural': 'Packaging Materials (Global)'},
        ),
        migrations.AlterUniqueTogether(
            name='packagingmaterial',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='packagingmaterial',
            name='name',
            field=models.CharField(help_text='Unique name for the packaging material (e.g., Foam Box A1, Gel Pack 500g).', max_length=150, unique=True),
        ),
        migrations.RemoveField(
            model_name='packagingmaterial',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='packagingmaterial',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='packagingmaterial',
            name='warehouse',
        ),
        migrations.CreateModel(
            name='WarehousePackagingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.PositiveIntegerField(default=0, help_text='Current available stock quantity.')),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Stock level at which to reorder.')),
                ('packaging_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stock', to='inventory.packagingmaterial')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_materials', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Packaging Material Stock',
                'verbose_name_plural': 'Warehouse Packaging Material Stocks',
                'ordering': ['warehouse__name', 'packaging_material__name'],
                'unique_together': {('packaging_material', 'warehouse')},
            },
        ),
    ]
