# Generated by Django 4.2.23 on 2025-08-06 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0022_alter_packagingmaterial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingStockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, help_text='Optional notes, e.g., PO number or reason for stock adjustment.', max_length=255, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse_packaging_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.warehousepackagingmaterial')),
            ],
            options={
                'verbose_name': 'Packaging Stock Transaction',
                'verbose_name_plural': 'Packaging Stock Transactions',
                'ordering': ['-received_at'],
            },
        ),
    ]
