# Generated by Django 4.2.23 on 2025-08-06 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0051_alter_packagingtype_options_packagingtype_warehouse_and_more'),
        ('inventory', '0023_packagingstocktransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagingstocktransaction',
            options={'ordering': ['-transaction_date'], 'verbose_name': 'Packaging Stock Transaction', 'verbose_name_plural': 'Packaging Stock Transactions'},
        ),
        migrations.RenameField(
            model_name='packagingstocktransaction',
            old_name='received_at',
            new_name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='packagingstocktransaction',
            name='quantity_received',
        ),
        migrations.RemoveField(
            model_name='packagingstocktransaction',
            name='received_by',
        ),
        migrations.AddField(
            model_name='packagingstocktransaction',
            name='quantity',
            field=models.IntegerField(default=0, help_text='The amount of stock moved. Positive for additions, negative for deductions.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagingstocktransaction',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_stock_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packagingstocktransaction',
            name='related_parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_stock_usages', to='operation.parcel'),
        ),
        migrations.AddField(
            model_name='packagingstocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock Received'), ('OUT', 'Stock Used (Packed)'), ('ADJ', 'Manual Adjustment')], default='IN', max_length=3),
        ),
    ]
