# Generated by Django 3.2.25 on 2025-05-18 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import operation.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0011_auto_20250515_1806'),
        ('inventory', '0012_auto_20250517_2331'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_code_system', models.CharField(blank=True, help_text="System's internal or user-defined code for this specific parcel, if different from main order parcel code.", max_length=50, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shipment Parcel',
                'verbose_name_plural': 'Shipment Parcels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParcelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_shipped_in_this_parcel', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Parcel Item',
                'verbose_name_plural': 'Parcel Items',
                'ordering': ['parcel', 'order_item'],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date', '-imported_at'], 'verbose_name': 'Customer Order', 'verbose_name_plural': 'Customer Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order', 'product__name'], 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='quantity_ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='inventory_updated',
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, help_text="Customer's company name (from file).", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, help_text="Customer's name (Address name from file).", max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='erp_order_id',
            field=models.CharField(default=0, help_text='Order ID from the ERP system or uploaded file.', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='imported_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='is_cold_chain',
            field=models.BooleanField(default=False, help_text='True if any item in the order requires cold chain shipping.'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='parcel_code',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_log',
            field=models.TextField(blank=True, help_text='Log of import/processing steps or errors.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_address_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_address_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_address_line1',
            field=models.CharField(blank=True, help_text='Street address from file.', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_address_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_address_zip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_notes',
            field=models.TextField(blank=True, help_text='Shipping specific notes from the file.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='title_notes',
            field=models.TextField(blank=True, help_text='Title/General notes from the file.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(help_text='Warehouse associated with this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='erp_product_name',
            field=models.CharField(blank=True, help_text='Product name as it appeared in the ERP/uploaded file.', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_cold_item',
            field=models.BooleanField(default=False, help_text='Does this specific item require cold chain handling (from ERP file).'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes specific to this order item processing.', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_allocated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_shipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING_ALLOCATION', 'Pending Allocation'), ('ALLOCATED', 'Stock Allocated'), ('ALLOCATION_FAILED', 'Allocation Failed'), ('READY_TO_SHIP', 'Ready to Ship'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='PENDING_ALLOCATION', max_length=25),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='suggested_batch_expiry_date_display',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='suggested_batch_item',
            field=models.ForeignKey(blank=True, help_text='The specific batch suggested or allocated for this order item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_order_items', to='inventory.inventorybatchitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='suggested_batch_number_display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='warehouse_product',
            field=models.ForeignKey(blank=True, help_text='The specific warehouse stock item for this product.', null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouseproduct'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(help_text='Date the order was placed, from the ERP file.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_IMPORT', 'Pending Import Data'), ('PENDING_ALLOCATION', 'Pending Allocation'), ('PARTIALLY_ALLOCATED', 'Partially Allocated'), ('FULLY_ALLOCATED', 'Fully Allocated'), ('PENDING_SHIPMENT', 'Pending Shipment'), ('PARTIALLY_SHIPPED', 'Partially Shipped'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('IMPORT_FAILED', 'Import Failed')], default='PENDING_IMPORT', help_text='Current status of the order processing.', max_length=25),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(help_text='The generic product.', on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.DeleteModel(
            name='Parcels',
        ),
        migrations.AddField(
            model_name='parcelitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='operation.orderitem'),
        ),
        migrations.AddField(
            model_name='parcelitem',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_parcel', to='operation.parcel'),
        ),
        migrations.AddField(
            model_name='parcelitem',
            name='shipped_from_batch',
            field=models.ForeignKey(blank=True, help_text='The specific inventory batch this parcel item was shipped from.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorybatchitem'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='operation.order'),
        ),
        migrations.AlterUniqueTogether(
            name='parcelitem',
            unique_together={('parcel', 'order_item', 'shipped_from_batch')},
        ),
    ]
