# Generated by Django 3.2.25 on 2025-05-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_alter_parcel_code_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='parcel_code',
            field=models.CharField(blank=True, help_text='Auto-generated unique code for this order/parcel group.', max_length=50, unique=True),
        ),
    ]
