# Generated by Django 3.2.25 on 2025-05-22 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0005_alter_order_parcel_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='parcel_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='order',
            name='order_display_code',
            field=models.CharField(blank=True, help_text='Auto-generated unique display code for this order. Used for internal reference before parcels are created.', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity_packed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parcel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_IMPORT', 'Pending Import Data'), ('PENDING_ALLOCATION', 'Pending Allocation'), ('PARTIALLY_ALLOCATED', 'Partially Allocated'), ('FULLY_ALLOCATED', 'Fully Allocated'), ('READY_FOR_PACKING', 'Ready for Packing'), ('PENDING_SHIPMENT', 'Pending Shipment'), ('PARTIALLY_SHIPPED', 'Partially Shipped'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('IMPORT_FAILED', 'Import Failed')], default='PENDING_IMPORT', help_text='Current status of the order processing.', max_length=25),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING_ALLOCATION', 'Pending Allocation'), ('ALLOCATED', 'Stock Allocated'), ('ALLOCATION_FAILED', 'Allocation Failed'), ('READY_TO_PACK', 'Ready to Pack'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='PENDING_ALLOCATION', max_length=25),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_code_system',
            field=models.CharField(blank=True, default=0, help_text="System's unique code for this specific parcel.", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
