# Generated by Django 3.2.25 on 2025-05-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20250522_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW ORDER', 'New'), ('PARTIALLY_SHIPPED', 'Partial'), ('FULLY_SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('DELIVERY_FAILED', 'Delivery Failed'), ('RETURNED_COURIER', 'Returned by Courier'), ('RETURNED_CUSTOM', 'Returned by Custom'), ('ADJUSTED_TO_CLOSE', 'Adjusted to Close'), ('INVOICE_ISSUED', 'Billed (Completed)')], default='NEW ORDER', help_text='Current status of the order processing.', max_length=25),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('NEW ORDER', 'New'), ('PARTIALLY_SHIPPED', 'Partial'), ('FULLY_SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('DELIVERY_FAILED', 'Delivery Failed'), ('RETURNED_COURIER', 'Returned by Courier'), ('RETURNED_CUSTOM', 'Returned by Custom'), ('ADJUSTED_TO_CLOSE', 'Adjusted to Close'), ('INVOICE_ISSUED', 'Billed (Completed)')], default='NEW ORDER', max_length=25),
        ),
    ]
