# Generated by Django 3.2.25 on 2025-05-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20250522_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity_returned_to_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parcel',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('PENDING_SHIPMENT', 'Pending Shipment'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('DELIVERY_FAILED', 'Delivery Failed'), ('RETURNED_COURIER', 'Returned by Courier'), ('CANCELLED', 'Cancelled')], default='PENDING_SHIPMENT', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_display_code',
            field=models.CharField(blank=True, help_text='Auto-generated unique display code for this order.', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW_ORDER', 'New'), ('PARTIALLY_SHIPPED', 'Partial'), ('FULLY_SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('DELIVERY_FAILED', 'Failed'), ('RETURNED_COURIER', 'Returned by Courier'), ('ADJUSTED_TO_CLOSE', 'Adjusted to Close'), ('INVOICE_ISSUED', 'Billed (Completed)')], default='NEW_ORDER', help_text='Current status of the order processing.', max_length=25),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING_PROCESSING', 'Pending Processing'), ('ALLOCATED', 'Stock Allocated'), ('PACKED', 'Packed in Parcel'), ('ITEM_SHIPPED', 'Item Shipped'), ('ITEM_DELIVERED', 'Item Delivered'), ('ITEM_DELIVERY_FAILED', 'Item Delivery Failed'), ('ITEM_RETURNED_RESTOCKED', 'Item Returned to Stock'), ('ITEM_CANCELLED', 'Item Cancelled'), ('ITEM_BILLED', 'Item Billed')], default='PENDING_PROCESSING', max_length=30),
        ),
    ]
