# Generated by Django 3.2.25 on 2025-05-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20250521_2317'),
        ('operation', '0008_auto_20250522_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_display_code',
            field=models.CharField(blank=True, help_text='Display code for this order. May be deprecated or generated upon packing.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='suggested_batch_item',
            field=models.ForeignKey(blank=True, help_text='The specific batch chosen and packed for this order item (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_order_items', to='inventory.inventorybatchitem'),
        ),
        migrations.AlterUniqueTogether(
            name='parcelitem',
            unique_together=set(),
        ),
    ]
