# Generated by Django 3.2.25 on 2025-05-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_auto_20250523_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity_allocated',
        ),
        migrations.AddField(
            model_name='parcel',
            name='billed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when parcel status changed to CANCELLED.', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING_PROCESSING', 'Pending Processing'), ('PACKED', 'Packed in Parcel'), ('ITEM_SHIPPED', 'Item Shipped'), ('ITEM_DELIVERED', 'Item Delivered'), ('ITEM_DELIVERY_FAILED', 'Item Delivery Failed'), ('ITEM_RETURNED_RESTOCKED', 'Item Returned & Restocked'), ('ITEM_CANCELLED', 'Item Cancelled'), ('ITEM_BILLED', 'Item Billed')], default='PENDING_PROCESSING', max_length=30),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('PREPARING_TO_PACK', 'Preparing to Pack'), ('READY_TO_SHIP', 'Ready to Ship'), ('PICKED_UP', 'Picked Up by Courier'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('DELIVERY_FAILED', 'Delivery Failed'), ('RETURNED_COURIER', 'Returned by Courier'), ('CANCELLED', 'Cancelled'), ('BILLED', 'Billed')], default='PENDING_SHIPMENT', max_length=25),
        ),
    ]
