# Generated by Django 3.2.25 on 2025-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_auto_20250526_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_notes',
            field=models.TextField(blank=True, help_text='Shipping specific notes from the file (used for Parcel Notes).', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING_PROCESSING', 'Pending Processing'), ('PACKED', 'Packed in Parcel'), ('ITEM_SHIPPED', 'Item Shipped'), ('ITEM_DELIVERED', 'Item Delivered'), ('ITEM_DELIVERY_FAILED', 'Item Delivery Failed'), ('ITEM_RETURNED_RESTOCKED', 'Item Returned to Stock'), ('ITEM_CANCELLED', 'Item Cancelled'), ('ITEM_BILLED', 'Item Billed')], default='PENDING_PROCESSING', max_length=30),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='returned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when parcel status changed to RETURNED_COURIER.', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='shipped_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when parcel status changed to PICKED_UP.', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('PREPARING_TO_PACK', 'Preparing to Pack'), ('READY_TO_SHIP', 'Ready to Ship'), ('PICKED_UP', 'Picked Up by Courier'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('DELIVERY_FAILED', 'Delivery Failed'), ('RETURNED_COURIER', 'Returned by Courier'), ('CANCELLED', 'Cancelled'), ('BILLED', 'Billed')], default='PREPARING_TO_PACK', max_length=25),
        ),
    ]
