# Generated by Django 3.2.25 on 2025-05-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_auto_20250526_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_removed_log',
            field=models.JSONField(blank=True, help_text="Log of items quantities 'removed' by user during editing of partially shipped orders. Stores a list of dicts, e.g., [{'order_item_id': id, 'product_sku': sku, 'removed_qty': X}, ...].", null=True),
        ),
    ]
