# Generated by Django 3.2.25 on 2025-05-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_order_items_removed_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='packaging_type',
            field=models.CharField(blank=True, choices=[('MEDICAL_BOX_A1', 'Medical Box - A1'), ('FLYER_S', 'Flyer S'), ('FLYER_M', 'Flyer M'), ('FLYER_L', 'Flyer L'), ('OTHER', 'Other/Unspecified')], help_text='Type of packaging used for this parcel.', max_length=20, null=True),
        ),
    ]
