# Generated by Django 3.2.25 on 2025-06-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_parcel_packaging_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='packaging_type',
            field=models.CharField(blank=True, choices=[('FOAM_BOX_A1', 'Foam Box A1'), ('FOAM_BOX_PLUS', 'Foam Box +Amb'), ('FLYER_S', 'Flyer S'), ('FLYER_M', 'Flyer M'), ('FLYER_L', 'Flyer L'), ('OTHER', 'Other/Unspecified')], help_text='Type of packaging used for this parcel.', max_length=20, null=True),
        ),
    ]
