# Generated by Django 3.2.25 on 2025-06-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_alter_parcel_packaging_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='customs_description',
            field=models.CharField(blank=True, help_text="Overall description for customs, e.g., 'Medical Supplies'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='declared_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total declared value for this parcel for customs.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AddField(
            model_name='parcelitem',
            name='customs_description',
            field=models.CharField(blank=True, help_text='Specific description for this item line for customs.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parcelitem',
            name='declared_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Declared value for this specific item line in the parcel.', max_digits=10, null=True),
        ),
    ]
