# Generated by Django 3.2.25 on 2025-06-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0016_auto_20250603_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the goods for customs purposes.', unique=True)),
                ('hs_code', models.CharField(help_text='Harmonized System (HS) code.', max_length=20, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customs Declaration',
                'verbose_name_plural': 'Customs Declarations',
                'ordering': ['description'],
            },
        ),
    ]
