# Generated by Django 3.2.25 on 2025-06-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0017_customsdeclaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='Short code for the courier, e.g., DHL, FEDEX', max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Courier Company',
                'verbose_name_plural': 'Courier Companies',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='CustomsDeclaration',
        ),
    ]
