# Generated by Django 3.2.25 on 2025-06-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_packagingmaterial'),
        ('operation', '0019_auto_20250603_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for the packaging type (e.g., 'Standard Cold Box Setup A')", max_length=150, unique=True)),
                ('type_code', models.CharField(blank=True, help_text="Short code for this packaging type (e.g., 'SCBA'). Can be used for quick selection or integration.", max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('environment_type', models.CharField(choices=[('COLD', 'Cold Chain'), ('AMBIENT', 'Ambient')], default='AMBIENT', max_length=20)),
                ('default_length_cm', models.DecimalField(decimal_places=2, help_text='Default assembled length for this packaging type.', max_digits=10)),
                ('default_width_cm', models.DecimalField(decimal_places=2, help_text='Default assembled width for this packaging type.', max_digits=10)),
                ('default_height_cm', models.DecimalField(decimal_places=2, help_text='Default assembled height for this packaging type.', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Only active packaging types can be selected for new parcels.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                # ('materials', models.ManyToManyField(blank=True, related_name='packaging_types', to='inventory.PackagingMaterial')),
            ],
            options={
                'verbose_name': 'Packaging Type',
                'verbose_name_plural': 'Packaging Types',
                'ordering': ['name'],
            },
        ),
    ]
