# Generated by Django 3.2.25 on 2025-06-05 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_packagingmaterial'),
        ('operation', '0020_packagingtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingTypeMaterialComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this material used in the packaging type.')),
                ('packaging_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.packagingmaterial')),
                ('packaging_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.packagingtype')),
            ],
            options={
                'verbose_name': 'Packaging Type Material Component',
                'verbose_name_plural': 'Packaging Type Material Components',
                'unique_together': {('packaging_type', 'packaging_material')},
            },
        ),
    ]
