# Generated by Django 3.2.25 on 2025-06-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_packagingmaterial'),
        ('operation', '0021_packagingtypematerialcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingtype',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='packaging_types', through='operation.PackagingTypeMaterialComponent', to='inventory.PackagingMaterial'),
        ),
    ]
