# Generated by Django 3.2.25 on 2025-06-06 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0022_packagingtype_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='packaging_type_fk',
            field=models.ForeignKey(blank=True, help_text='The new packaging type relationship.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.packagingtype'),
        ),
    ]
