# Generated by Django 3.2.25 on 2025-06-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0023_parcel_packaging_type_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='packaging_type',
        ),
    ]
