# Generated by Django 3.2.25 on 2025-06-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0024_remove_parcel_packaging_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='packaging_type_fk',
            new_name='packaging_type',
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='default_length_cm',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
