# Generated by Django 3.2.25 on 2025-06-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0025_auto_20250606_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingtype',
            name='default_height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='default_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='default_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='type_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
