# Generated by Django 3.2.25 on 2025-06-08 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0026_auto_20250608_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='operation.couriercompany'),
        ),
    ]
