# Generated by Django 3.2.25 on 2025-06-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0027_parcel_courier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='courier',
            new_name='courier_company',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='courier_name',
        ),
    ]
