# Generated by Django 3.2.25 on 2025-06-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0028_auto_20250608_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='couriercompany',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck this to hide the courier from selection lists.'),
        ),
    ]
