# Generated by Django 3.2.25 on 2025-06-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0029_couriercompany_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customsdeclaration',
            options={'ordering': ['description'], 'verbose_name': 'Customs Declaration', 'verbose_name_plural': 'Customs Declarations'},
        ),
        migrations.RemoveConstraint(
            model_name='customsdeclaration',
            name='unique_decl_with_courier_desc_hs_type',
        ),
        migrations.RemoveConstraint(
            model_name='customsdeclaration',
            name='unique_decl_without_courier_desc_hs_type',
        ),
        migrations.RemoveField(
            model_name='customsdeclaration',
            name='courier_company',
        ),
        migrations.RemoveField(
            model_name='customsdeclaration',
            name='shipment_type',
        ),
        migrations.AddField(
            model_name='customsdeclaration',
            name='applies_to_ambient',
            field=models.BooleanField(default=False, verbose_name='Applies to Ambient Only Shipments'),
        ),
        migrations.AddField(
            model_name='customsdeclaration',
            name='applies_to_cold_chain',
            field=models.BooleanField(default=False, verbose_name='Applies to Cold Chain Only Shipments'),
        ),
        migrations.AddField(
            model_name='customsdeclaration',
            name='applies_to_mix',
            field=models.BooleanField(default=False, verbose_name='Applies to Mixed Shipments (Cold + Ambient)'),
        ),
        migrations.AddField(
            model_name='customsdeclaration',
            name='courier_companies',
            field=models.ManyToManyField(blank=True, help_text='Select couriers this applies to. Leave blank if generic for all couriers.', related_name='customs_declarations', to='operation.CourierCompany'),
        ),
        migrations.AlterField(
            model_name='customsdeclaration',
            name='description',
            field=models.TextField(help_text='Unique description of the goods for customs purposes.'),
        ),
        migrations.AddConstraint(
            model_name='customsdeclaration',
            constraint=models.UniqueConstraint(fields=('description', 'hs_code'), name='unique_desc_hs_code_pair'),
        ),
    ]
