# Generated by Django 3.2.25 on 2025-06-11 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0030_auto_20250609_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='customs_description',
        ),
        migrations.AddField(
            model_name='parcel',
            name='customs_declaration',
            field=models.ForeignKey(blank=True, help_text='The selected customs declaration for this parcel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='operation.customsdeclaration'),
        ),
    ]
