# Generated by Django 3.2.25 on 2025-06-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('operation', '0031_auto_20250611_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recipient_address_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recipient_address_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recipient_address_line1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recipient_address_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recipient_address_zip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recipient_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vat_number',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer'),
        ),
    ]
