# Generated by Django 3.2.25 on 2025-06-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0032_auto_20250611_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated shipping cost for this parcel.', max_digits=10, null=True),
        ),
    ]
