# Generated by Django 3.2.25 on 2025-06-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0033_parcel_estimated_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='declared_value_myr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Automatically calculated declared value in MYR based on the USD value.', max_digits=10, null=True, verbose_name='Declared Value (MYR)'),
        ),
    ]
