# Generated by Django 3.2.25 on 2025-06-13 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0034_parcel_declared_value_myr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelTrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='The date and time of the tracking event.')),
                ('status_description', models.CharField(help_text="The description of the event, e.g., 'Departed from Facility'.", max_length=255)),
                ('location', models.CharField(blank=True, help_text='The location where the event occurred.', max_length=255, null=True)),
                ('event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='operation.parcel')),
            ],
            options={
                'verbose_name': 'Parcel Tracking Log',
                'verbose_name_plural': 'Parcel Tracking Logs',
                'ordering': ['-timestamp'],
                'unique_together': {('parcel', 'event_id')},
            },
        ),
    ]
