# Generated by Django 3.2.25 on 2025-06-19 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0035_parceltrackinglog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('invoice_file', models.FileField(upload_to='courier_invoices/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('courier_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operation.couriercompany')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='parcel',
            name='actual_shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW_ORDER', 'New'), ('PARTIALLY_SHIPPED', 'Partial'), ('FULLY_SHIPPED', 'Shipped'), ('ADJUSTED_TO_CLOSE', 'Adjusted to Close')], default='NEW_ORDER', help_text='Current status of the order processing.', max_length=25),
        ),
        migrations.CreateModel(
            name='CourierInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('actual_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_billed_to_customer', models.BooleanField(default=False)),
                ('courier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operation.courierinvoice')),
                ('parcel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_item', to='operation.parcel')),
            ],
        ),
    ]
