# Generated by Django 3.2.25 on 2025-06-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0037_auto_20250619_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierinvoiceitem',
            name='billed_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight (kg)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='courierinvoiceitem',
            name='scale_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DHL Scale Weight (B)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='courierinvoiceitem',
            name='vol_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DHL Vol Weight (W)', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='courierinvoiceitem',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, help_text='The cumulative cost for this tracking number across all invoices.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='courierinvoiceitem',
            name='courier_invoice',
            field=models.ForeignKey(help_text='The most recent invoice this tracking number appeared on.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operation.courierinvoice'),
        ),
        migrations.AlterField(
            model_name='courierinvoiceitem',
            name='tracking_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='courierinvoiceitem',
            index=models.Index(fields=['tracking_number'], name='operation_c_trackin_7f510a_idx'),
        ),
    ]
