# Generated by Django 3.2.25 on 2025-06-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0038_auto_20250620_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierinvoiceitem',
            name='cost_history',
            field=models.JSONField(blank=True, default=list, help_text='A list of all charges from individual invoices.'),
        ),
        migrations.AlterField(
            model_name='courierinvoiceitem',
            name='tracking_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
