# Generated by Django 3.2.25 on 2025-06-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0039_auto_20250620_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierinvoiceitem',
            name='receiver_state',
            field=models.CharField(blank=True, help_text='The state/province of the receiver from the invoice.', max_length=100, null=True),
        ),
    ]
