# Generated by Django 3.2.25 on 2025-06-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0040_courierinvoiceitem_receiver_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierinvoiceitem',
            name='destination_name',
            field=models.CharField(blank=True, help_text='The destination name from the invoice file.', max_length=255, null=True),
        ),
    ]
