# Generated by Django 3.2.25 on 2025-06-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0041_courierinvoiceitem_destination_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierinvoiceitem',
            name='dispute_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courierinvoiceitem',
            name='dispute_history',
            field=models.JSONField(blank=True, default=list, help_text='A list of updates with dates and remarks for the dispute.'),
        ),
        migrations.AddField(
            model_name='courierinvoiceitem',
            name='final_amount_after_dispute',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='courierinvoiceitem',
            name='final_amount_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
