# Generated by Django 3.2.25 on 2025-07-08 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0042_auto_20250625_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceltrackinglog',
            name='event_id',
            field=models.CharField(default=uuid.uuid4, help_text='A unique identifier for the tracking event from the courier API to prevent duplicates.', max_length=255, unique=True),
        ),
    ]
