# Generated by Django 3.2.25 on 2025-07-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0043_alter_parceltrackinglog_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
