# Generated by Django 3.2.25 on 2025-07-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0044_alter_parcel_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierinvoice',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=10),
        ),
    ]
