# Generated by Django 3.2.25 on 2025-07-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0045_courierinvoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated as Invoice Amount - Payment Amount. Can be negative for overpayments.', max_digits=10),
        ),
        migrations.AddField(
            model_name='courierinvoice',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The actual amount paid for this invoice.', max_digits=10, null=True),
        ),
    ]
