# Generated by Django 4.2.23 on 2025-07-31 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_stocktransaction_transaction_type'),
        ('operation', '0046_auto_20250727_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_name', models.CharField(db_index=True, help_text='The exact product name from the source Excel file.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('mapped_product', models.ForeignKey(help_text='The system product that the imported name maps to.', on_delete=django.db.models.deletion.CASCADE, related_name='import_mappings', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Product Import Mapping',
                'verbose_name_plural': 'Product Import Mappings',
                'ordering': ['-last_used_at'],
            },
        ),
    ]
