# Generated by Django 4.2.23 on 2025-08-01 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_warehouseproduct_selling_price'),
        ('operation', '0047_productmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierinvoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='The warehouse this invoice belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courier_invoices', to='warehouse.warehouse'),
        ),
    ]
