# Generated by Django 4.2.23 on 2025-08-04 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_warehouseproduct_selling_price'),
        ('operation', '0048_courierinvoice_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsdeclaration',
            name='warehouse',
            field=models.ForeignKey(help_text='The warehouse this declaration is for.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customs_declarations', to='warehouse.warehouse'),
        ),
    ]
