# Generated by Django 4.2.23 on 2025-08-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0049_customsdeclaration_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsdeclaration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck this to deactivate the declaration.'),
        ),
    ]
