# Generated by Django 4.2.23 on 2025-08-06 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_warehouseproduct_selling_price'),
        ('inventory', '0022_alter_packagingmaterial_options_and_more'),
        ('operation', '0050_customsdeclaration_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagingtype',
            options={'ordering': ['warehouse__name', 'name'], 'verbose_name': 'Packaging Type', 'verbose_name_plural': 'Packaging Types'},
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='warehouse',
            field=models.ForeignKey(default=1, help_text='The warehouse this packaging type belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='packaging_types', to='warehouse.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='packaging_types_as_component', through='operation.PackagingTypeMaterialComponent', to='inventory.packagingmaterial'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='type_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='packagingtype',
            unique_together={('name', 'warehouse')},
        ),
    ]
