# Generated by Django 3.2.25 on 2025-06-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, help_text='Unique internal customer ID', max_length=20, unique=True)),
                ('customer_name', models.CharField(db_index=True, max_length=255)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, help_text='Unique phone number to identify customers.', max_length=30, null=True, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the customer.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['customer_name', 'company_name'],
            },
        ),
    ]
